### ISSUE TITLE
SASS error (not valid CSS value)

### ISSUE THREAD

**Issue by mciszczon** [primocss/primocss#18]
Hi!

I installed PrimoCSS using yarn and wanted to compile it straight away and got this error. I haven't done any changes to it. Below is the error thrown by sass:

````
error node_modules/primocss/scss/_tools.breakpoints.scss (Line 41: (xs: 320px, sm: 420px, md: 768px, lg: 1024px, xl: 1280px) isn't a valid CSS value.)
````

**Comment by richmccartney** [comment]
Thank you @mciszczon for raising this issue, I'll look into it this week 👍

**Comment by mciszczon** [comment]
Hi, any news on this issue? I would like to start working on a project and I'm currently on hold due to this.

Let me know if I could help in any way, PrimoCSS looks really neat and it would be pity if it went extinct. I saw that the website is no longer up and running, which is sad. Keep up the great work!

**Comment by richmccartney** [comment]
Hi @mciszczon can you try pulling down master and seeing if this persists now? I've essentially removed the prefix function that wasn't really needed as in grids we already loop through the `$breakpoint`. Thus it just added extra complexity for the sake of having it. 

The framework is for sure still active, I'm re-building the documentation I just haven't put up a holding page yet (very busy at Monzo 😄)

**Comment by richmccartney** [comment]
Okay tested this with Node sass / LibSass, Sass 3.4.21 should all compile now.

**Comment by richmccartney** [comment]
Plublished https://www.npmjs.com/package/primocss

**Comment by mciszczon** [comment]
Yup, all workin' now. Thanks a lot, man, love it!

I'll let you know when the project goes live, you may use it for some kind of showcase page or maybe _PrimoCSS in the wild_ (sounds great!).
